import {
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  FileText,
  Target,
  Type,
  Layout,
  Search,
} from "lucide-react";

export default function ResumeAnalysis({ result, onBack }) {
  if (!result) return null;

  const scores = result.scores || {};

  return (
    <div className="max-w-6xl mx-auto space-y-6">

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles
              size={18}
              className="text-[#19714e]"
            />

            <span className="text-xs font-bold uppercase tracking-wider text-[#19714e]">
              AI Resume Analysis
            </span>
          </div>

          <h2 className="text-3xl font-bold font-['Space_Grotesk'] text-[#12221d]">
            Resume Analysis
          </h2>

          <p className="text-sm text-[#68756f] mt-2">
            Detailed feedback generated by AI.
          </p>
        </div>

        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2.5 rounded-xl border border-[#dfe7e2] text-xs font-semibold text-[#52615a] hover:bg-[#f7faf8] flex items-center gap-2"
        >
          <ArrowLeft size={15} />
          Analyze Another
        </button>
      </div>

      {/* Score Overview */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Overall Score */}
        <div className="bg-[#123c2c] text-white rounded-3xl p-8">
          <p className="text-xs font-semibold uppercase tracking-wider opacity-70">
            Overall Score
          </p>

          <div className="flex items-end gap-2 mt-4">
            <span className="text-6xl font-bold font-['Space_Grotesk']">
              {result.overall_score}
            </span>

            <span className="text-lg opacity-60 mb-2">
              /100
            </span>
          </div>

          <div className="mt-5 h-2 bg-white/20 rounded-full overflow-hidden">
            <div
              className="h-full bg-white rounded-full"
              style={{
                width: `${result.overall_score}%`,
              }}
            />
          </div>
        </div>

        {/* Summary */}
        <div className="lg:col-span-2 bg-white border border-[#dfe7e2] rounded-3xl p-8">
          <div className="flex items-center gap-2 mb-4">
            <FileText
              size={18}
              className="text-[#19714e]"
            />

            <h3 className="text-sm font-bold text-[#12221d]">
              Executive Summary
            </h3>
          </div>

          <p className="text-sm leading-7 text-[#52615a]">
            {result.summary}
          </p>
        </div>
      </div>

      {/* Score Cards */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">

        <ScoreCard
          title="Grammar"
          score={scores.grammar}
          icon={<Type size={17} />}
        />

        <ScoreCard
          title="Structure"
          score={scores.structure}
          icon={<Layout size={17} />}
        />

        <ScoreCard
          title="Formatting"
          score={scores.formatting}
          icon={<FileText size={17} />}
        />

        <ScoreCard
          title="Content"
          score={scores.content}
          icon={<Target size={17} />}
        />

        <ScoreCard
          title="ATS"
          score={scores.ats}
          icon={<Search size={17} />}
        />

      </div>

      {/* Strengths & Weaknesses */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* Strengths */}
        <div className="bg-white border border-[#dfe7e2] rounded-3xl p-7">

          <div className="flex items-center gap-2 mb-5">
            <CheckCircle2
              size={19}
              className="text-[#19714e]"
            />

            <h3 className="text-lg font-bold text-[#12221d]">
              Strengths
            </h3>
          </div>

          <div className="space-y-3">
            {(result.strengths || []).map((item, index) => (
              <div
                key={index}
                className="flex gap-3 p-3 rounded-xl bg-[#dff8eb]/50"
              >
                <CheckCircle2
                  size={16}
                  className="text-[#19714e] mt-0.5 shrink-0"
                />

                <p className="text-xs text-[#52615a] leading-5">
                  {item}
                </p>
              </div>
            ))}
          </div>

        </div>

        {/* Weaknesses */}
        <div className="bg-white border border-[#dfe7e2] rounded-3xl p-7">

          <div className="flex items-center gap-2 mb-5">
            <AlertTriangle
              size={19}
              className="text-amber-600"
            />

            <h3 className="text-lg font-bold text-[#12221d]">
              Areas to Improve
            </h3>
          </div>

          <div className="space-y-3">
            {(result.weaknesses || []).map((item, index) => (
              <div
                key={index}
                className="flex gap-3 p-3 rounded-xl bg-amber-50"
              >
                <AlertTriangle
                  size={16}
                  className="text-amber-600 mt-0.5 shrink-0"
                />

                <p className="text-xs text-[#52615a] leading-5">
                  {item}
                </p>
              </div>
            ))}
          </div>

        </div>

      </div>

      {/* Grammar */}
      <AnalysisSection
        title="Grammar Analysis"
        icon={<Type size={18} />}
      >
        <div className="flex items-center gap-3 mb-5">
          <div className="text-3xl font-bold text-[#12221d]">
            {result.grammar_analysis?.total_errors || 0}
          </div>

          <span className="text-xs text-[#68756f]">
            grammar errors found
          </span>
        </div>

        {(result.grammar_analysis?.errors || []).length === 0 ? (
          <div className="p-4 rounded-xl bg-[#dff8eb] text-xs text-[#19714e] font-semibold">
            No grammar errors detected.
          </div>
        ) : (
          result.grammar_analysis.errors.map((error, index) => (
            <div
              key={index}
              className="p-4 bg-red-50 rounded-xl text-xs text-red-700 mb-2"
            >
              {typeof error === "string"
                ? error
                : JSON.stringify(error)}
            </div>
          ))
        )}
      </AnalysisSection>

      {/* Structure */}
      <AnalysisSection
        title="Structure Analysis"
        icon={<Layout size={18} />}
      >
        <ListSection
          title="Missing Sections"
          items={result.structure_analysis?.missing_sections}
        />

        <ListSection
          title="Recommendations"
          items={result.structure_analysis?.recommendations}
        />
      </AnalysisSection>

      {/* Formatting */}
      <AnalysisSection
        title="Formatting Analysis"
        icon={<FileText size={18} />}
      >
        <ListSection
          title="Issues"
          items={result.formatting_analysis?.issues}
        />

        <ListSection
          title="Recommendations"
          items={result.formatting_analysis?.recommendations}
        />
      </AnalysisSection>

      {/* Content */}
      <AnalysisSection
        title="Content Analysis"
        icon={<Target size={18} />}
      >
        <ListSection
          title="Weak Statements"
          items={result.content_analysis?.weak_statements}
        />

        <ListSection
          title="Missing Information"
          items={result.content_analysis?.missing_information}
        />

        {result.content_analysis?.improved_versions?.length > 0 && (
          <div className="mt-6">
            <h4 className="text-xs font-bold text-[#12221d] mb-3">
              Improved Versions
            </h4>

            <div className="space-y-3">
              {result.content_analysis.improved_versions.map(
                (item, index) => (
                  <div
                    key={index}
                    className="p-4 rounded-xl bg-[#dff8eb]/50 text-xs text-[#52615a] leading-6"
                  >
                    {item}
                  </div>
                )
              )}
            </div>
          </div>
        )}
      </AnalysisSection>

      {/* ATS */}
      <AnalysisSection
        title="ATS Analysis"
        icon={<Search size={18} />}
      >
        <div className="flex items-center gap-3 mb-5">
          <div
            className={`px-4 py-2 rounded-xl text-xs font-bold ${
              result.ats_analysis?.ats_friendly
                ? "bg-[#dff8eb] text-[#19714e]"
                : "bg-red-50 text-red-600"
            }`}
          >
            {result.ats_analysis?.ats_friendly
              ? "ATS Friendly"
              : "Needs ATS Improvement"}
          </div>
        </div>

        <ListSection
          title="ATS Issues"
          items={result.ats_analysis?.issues}
        />
      </AnalysisSection>

      {/* Suggestions */}
      <div className="bg-white border border-[#dfe7e2] rounded-3xl p-7">

        <div className="flex items-center gap-2 mb-7">
          <Sparkles
            size={20}
            className="text-[#19714e]"
          />

          <h3 className="text-xl font-bold text-[#12221d]">
            AI Recommendations
          </h3>
        </div>

        <SuggestionGroup
          title="High Priority"
          items={result.suggestions?.high_priority}
        />

        <SuggestionGroup
          title="Medium Priority"
          items={result.suggestions?.medium_priority}
        />

        <SuggestionGroup
          title="Low Priority"
          items={result.suggestions?.low_priority}
        />

      </div>

    </div>
  );
}